package examen2p2_lloydcooperrr;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class frameMain extends javax.swing.JFrame {

    private ArrayList <Cliente> clientes = new ArrayList();
    private ArrayList <Artista> artistas = new ArrayList();
    private ArrayList <Lanzamiento> lanzamientos = new ArrayList();
    private ArrayList <ListasDeReproduccion> listasDeReproduccion = new ArrayList();
    private ArrayList <Cancion> canciones = new ArrayList();
    Artista artista;
    Cliente cliente;
    ListasDeReproduccion LDR;
    adminBarra ab;
    Cancion cancion;

    public frameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        readArtists();
        readClients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogArtistas = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCrearLanzamiento = new javax.swing.JButton();
        tfTituloLanzamiento = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnModificarLanzamiento = new javax.swing.JButton();
        tfNuevoTituloLanzamiento = new javax.swing.JTextField();
        dateChooserModify = new com.toedter.calendar.JDateChooser();
        cbLanzamientos = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btnEliminarLanzamiento = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tfNombreAlbum = new javax.swing.JTextField();
        dateChooserAlbum = new com.toedter.calendar.JDateChooser();
        btnCrearAlbum = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfNombreSingle = new javax.swing.JTextField();
        dateChooserSingle = new com.toedter.calendar.JDateChooser();
        btnCrearSingle = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tfNombreCancion = new javax.swing.JTextField();
        btnCrearCancion = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        spinnerTiempoDuracion = new javax.swing.JSpinner();
        cbAlbumes = new javax.swing.JComboBox<>();
        cbSingles = new javax.swing.JComboBox<>();
        rbSingle = new javax.swing.JRadioButton();
        rbAlbum = new javax.swing.JRadioButton();
        dialogRegister = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwfContraseñaArtista = new javax.swing.JPasswordField();
        tfUsuarioArtista = new javax.swing.JTextField();
        tfEdadArtista = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNombreArtistico = new javax.swing.JTextField();
        btnRegisterArtist = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tfEdadCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pwfContraseñaCliente = new javax.swing.JPasswordField();
        tfUsuarioCliente = new javax.swing.JTextField();
        btnRegisterClient = new javax.swing.JButton();
        dialogClientes = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tfNombreDeLista = new javax.swing.JTextField();
        btnCrearListaRP = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCanciones = new javax.swing.JList<>();
        cbListasRP = new javax.swing.JComboBox<>();
        tfNuevoNombreListaRP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnEliminarListaRP = new javax.swing.JButton();
        btnModificarListaRP = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        pbReproduccion = new javax.swing.JProgressBar();
        btnReproducir = new javax.swing.JButton();
        comboBoxAlbumes = new javax.swing.JComboBox<>();
        comboBoxSingles = new javax.swing.JComboBox<>();
        cbCanciones = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pwfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Titulo");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Fecha de lanzamiento");

        btnCrearLanzamiento.setText("Crear lanzamiento");
        btnCrearLanzamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearLanzamientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTituloLanzamiento)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTituloLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrearLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear lanzamiento", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Publicar lanzamiento", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Titulo");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha de lanzamiento");

        btnModificarLanzamiento.setText("Modificar lanzamiento");
        btnModificarLanzamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarLanzamientoMouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Lanzamiento");

        btnEliminarLanzamiento.setText("Eliminar lanzamiento");
        btnEliminarLanzamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarLanzamientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbLanzamientos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNuevoTituloLanzamiento)
                            .addComponent(dateChooserModify, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnModificarLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLanzamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfNuevoTituloLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(dateChooserModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jTabbedPane2.addTab("Editar/Eliminar lanzamiento", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnCrearAlbum.setText("Crear album");
        btnCrearAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearAlbumMouseClicked(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Nombre del album");

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Fecha de lanzamiento");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnCrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addComponent(btnCrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear album", jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Fecha de lanzamiento");

        btnCrearSingle.setText("Crear single");
        btnCrearSingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearSingleMouseClicked(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Nombre del single");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombreSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnCrearSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreSingle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserSingle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(btnCrearSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear single", jPanel10);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Tiempo de duracion");

        btnCrearCancion.setText("Crear cancion");
        btnCrearCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCancionMouseClicked(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Nombre de la cancion");

        spinnerTiempoDuracion.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 10));

        rbSingle.setText("Single");

        rbAlbum.setText("Album");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(rbAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(cbAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSingles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombreCancion)
                                    .addComponent(spinnerTiempoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSingle))
                    .addComponent(btnCrearCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(spinnerTiempoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSingle)
                    .addComponent(rbAlbum))
                .addGap(21, 21, 21)
                .addComponent(btnCrearCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear cancion", jPanel12);

        javax.swing.GroupLayout dialogArtistasLayout = new javax.swing.GroupLayout(dialogArtistas.getContentPane());
        dialogArtistas.getContentPane().setLayout(dialogArtistasLayout);
        dialogArtistasLayout.setHorizontalGroup(
            dialogArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        dialogArtistasLayout.setVerticalGroup(
            dialogArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Edad");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre artistico");

        btnRegisterArtist.setText("Registrar como artista");
        btnRegisterArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterArtistMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwfContraseñaArtista)
                            .addComponent(tfUsuarioArtista)
                            .addComponent(tfEdadArtista)
                            .addComponent(tfNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfUsuarioArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pwfContraseñaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfEdadArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegisterArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Artista", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Usuario");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Contraseña");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Edad");

        btnRegisterClient.setText("Registrarse como cliente");
        btnRegisterClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterClientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUsuarioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(pwfContraseñaCliente)
                    .addComponent(tfEdadCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnRegisterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfUsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pwfContraseñaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfEdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegisterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel4);

        javax.swing.GroupLayout dialogRegisterLayout = new javax.swing.GroupLayout(dialogRegister.getContentPane());
        dialogRegister.getContentPane().setLayout(dialogRegisterLayout);
        dialogRegisterLayout.setHorizontalGroup(
            dialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        dialogRegisterLayout.setVerticalGroup(
            dialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Nombre de la lista");

        btnCrearListaRP.setText("Crear lista de reproduccion");
        btnCrearListaRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearListaRPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearListaRP, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombreDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(btnCrearListaRP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Crear listas de reproduccion", jPanel2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(jListCanciones);

        cbListasRP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbListasRPItemStateChanged(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Nuevo nombre");

        btnEliminarListaRP.setText("Eliminar lista de reproduccion");
        btnEliminarListaRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarListaRPMouseClicked(evt);
            }
        });

        btnModificarListaRP.setText("Modificar lista de reproduccion");
        btnModificarListaRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarListaRPMouseClicked(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Listas de reproduccion");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbListasRP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(tfNuevoNombreListaRP)
                            .addComponent(btnEliminarListaRP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarListaRP))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(1, 1, 1)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cbListasRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(tfNuevoNombreListaRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarListaRP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarListaRP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Editar/Eliminar listas", jPanel9);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Ver listas", jPanel11);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        btnReproducir.setText("Reproducir");
        btnReproducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReproducirMouseClicked(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Cancion");

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Single");

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Album");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(btnReproducir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxSingles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(cbCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pbReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Reproduccion de musica", jPanel13);

        javax.swing.GroupLayout dialogClientesLayout = new javax.swing.GroupLayout(dialogClientes.getContentPane());
        dialogClientes.getContentPane().setLayout(dialogClientesLayout);
        dialogClientesLayout.setHorizontalGroup(
            dialogClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        dialogClientesLayout.setVerticalGroup(
            dialogClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");

        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artista", "Cliente" }));

        btnRegister.setText("Register");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUser)
                            .addComponent(pwfPassword)
                            .addComponent(cbTipo, 0, 250, Short.MAX_VALUE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnRegister))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        if (tfUser.getText().isEmpty() || pwfPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos campos");
        } else if (cbTipo.getSelectedIndex() == 0) {
            for (Artista a : artistas) {
                if (a.getUsername().equals(tfUser.getText()) && a.getPassword().equals(pwfPassword.getText())) {
                    artista = a;
                    dialogArtistas.pack();
                    dialogArtistas.setModal(true);
                    dialogArtistas.setLocationRelativeTo(this);
                    dialogArtistas.setVisible(true);
                    tfUser.setText("");
                    pwfPassword.setText("");
                    
                }
            }
        } else if (cbTipo.getSelectedIndex() == 1) {
            for (Cliente c : clientes) {
                if (c.getUsername().equals(tfUser.getText()) && c.getPassword().equals(pwfPassword.getText())) {
                    cliente = c;
                    dialogClientes.pack();
                    dialogClientes.setModal(true);
                    dialogClientes.setLocationRelativeTo(this);
                    dialogClientes.setVisible(true);
                    tfUser.setText("");
                    pwfPassword.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Intentelo de nuevo");
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        dialogRegister.pack();
        dialogRegister.setModal(true);
        dialogRegister.setLocationRelativeTo(this);
        dialogRegister.setVisible(true);
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnRegisterClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterClientMouseClicked
        String user = tfUsuarioCliente.getText();
        String clientPassword = pwfContraseñaCliente.getText();
        int edadCliente = Integer.parseInt(tfEdadCliente.getText());
        boolean exists = false;

        if (edadCliente <= 12) {
            JOptionPane.showMessageDialog(dialogRegister, "Debe ser mayor de 12 años");
        } else {
            for (Cliente cliente : clientes) {
                if (cliente.getUsername().equals(user)) {
                    exists = true;
                    break;
                }
            }
            if (!exists) {
                clientes.add(new Cliente("Cliente", user, clientPassword, edadCliente));
                updateClients();
                bitacora(user, "Cliente");
                JOptionPane.showMessageDialog(dialogRegister, "Registrado correctamente");
                tfUsuarioCliente.setText("");
                pwfContraseñaCliente.setText("");
                tfEdadCliente.setText("");
            } else {
                JOptionPane.showMessageDialog(dialogRegister, "El usuario ya existe");
            }
        }
    }//GEN-LAST:event_btnRegisterClientMouseClicked

    private void btnRegisterArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterArtistMouseClicked
        if (tfUsuarioArtista.getText().isEmpty() || pwfContraseñaArtista.getText().isEmpty()
                || tfEdadArtista.getText().isEmpty() || tfNombreArtistico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(dialogRegister, "Debe llenar todos los campos");
        } else {
            String user = tfUsuarioArtista.getText();
            String artistPassword = pwfContraseñaArtista.getText();
            int edadArtista = Integer.parseInt(tfEdadArtista.getText());
            String nombreArtistico = tfNombreArtistico.getText();
            boolean exists = false;

            if (edadArtista < 18) {
                JOptionPane.showMessageDialog(dialogRegister, "Debe tener 18 o mas años");
            } else {
                for (Cliente cliente : clientes) {
                    if (cliente.getUsername().equals(user)) {
                        exists = true;
                        break;
                    }
                }
                if (!exists) {
                    artistas.add(new Artista(nombreArtistico, "Artista", user, artistPassword, edadArtista));
                    updateArtists();
                    bitacora(user, "Artista");
                    JOptionPane.showMessageDialog(dialogRegister, "Registrado correctamente");
                    tfUsuarioArtista.setText("");
                    pwfContraseñaArtista.setText("");
                    tfEdadArtista.setText("");
                    tfNombreArtistico.setText("");
                } else {
                    JOptionPane.showMessageDialog(dialogRegister, "El usuario ya existe");
                }
            }
        }
    }//GEN-LAST:event_btnRegisterArtistMouseClicked

    private void btnCrearLanzamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLanzamientoMouseClicked
        if (tfTituloLanzamiento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(dialogArtistas, "Debe llenar todos los campos");
        } else {
            String tituloLanzamiento = tfTituloLanzamiento.getText();
            Date fechaLanzamiento = dateChooser.getDate();

            lanzamientos.add(new Lanzamiento(tituloLanzamiento, fechaLanzamiento, 0));
            cbLanzamientos.setModel(actualizarComboBoxLanzamientos());
            updateArtists();
            JOptionPane.showMessageDialog(dialogArtistas, "Lanzamiento creado correctamente");
            tfTituloLanzamiento.setText("");
        }
    }//GEN-LAST:event_btnCrearLanzamientoMouseClicked

    private void btnModificarLanzamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarLanzamientoMouseClicked
        if (tfNuevoTituloLanzamiento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar los campos");
        } else {
            String nuevoTitulo = tfNuevoTituloLanzamiento.getText();
            Date nuevaFecha = dateChooser.getDate();

            artista.getAlbumesPublicados().get(cbLanzamientos.getSelectedIndex()).setTituloDePublicacion(nuevoTitulo);
            artista.getAlbumesPublicados().get(cbLanzamientos.getSelectedIndex()).setFechaDeLanzamiento(nuevaFecha);
            updateArtists();
            JOptionPane.showMessageDialog(this, "Lanzamiento modificado correctamente");
        }
    }//GEN-LAST:event_btnModificarLanzamientoMouseClicked

    private void btnCrearListaRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearListaRPMouseClicked
        if (tfNombreDeLista.getText().isEmpty()) {
            JOptionPane.showMessageDialog(dialogClientes, "Llene todos los campos");
        } else {
            String tituloLista = tfNombreDeLista.getText();
            listasDeReproduccion.add(new ListasDeReproduccion(tituloLista, 0));
            updateClients();
            cbListasRP.setModel(actualizarComboBoxListasRP());
            JOptionPane.showMessageDialog(dialogClientes, "Lista de reproduccion creada correctamente");
        }
    }//GEN-LAST:event_btnCrearListaRPMouseClicked

    private void btnEliminarLanzamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarLanzamientoMouseClicked
        if (cbListasRP.getSelectedIndex() >= 0) {
            artistas.remove(cbLanzamientos.getSelectedIndex());
            actualizarComboBoxLanzamientos();
            updateArtists();
            JOptionPane.showMessageDialog(dialogArtistas, "Lanzamiento eliminado correctamente");
        }
    }//GEN-LAST:event_btnEliminarLanzamientoMouseClicked

    private void btnEliminarListaRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarListaRPMouseClicked
        listasDeReproduccion.remove(cbListasRP.getSelectedIndex());
        updateClients();
        cbListasRP.setModel(actualizarComboBoxListasRP());
        JOptionPane.showMessageDialog(dialogClientes, "Lista eliminada correctamente");
    }//GEN-LAST:event_btnEliminarListaRPMouseClicked

    private void btnModificarListaRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarListaRPMouseClicked
        
        if (tfNuevoTituloLanzamiento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar los campos");
        } else {
            String nuevoNombre = tfNuevoNombreListaRP.getText();
            
            //LDR
            JOptionPane.showMessageDialog(this, "Lanzamiento modificado correctamente");
        }
    }//GEN-LAST:event_btnModificarListaRPMouseClicked

    private void cbListasRPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbListasRPItemStateChanged
        if (cbListasRP.getSelectedIndex() >= 0) {
           jListCanciones.setModel(actualizarList());
           updateClients();
        }
    }//GEN-LAST:event_cbListasRPItemStateChanged

    private void btnCrearAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearAlbumMouseClicked
        if (tfNombreAlbum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(dialogClientes, "Debe llenar todos los campos");
        } else {
            artistas.get(artistas.indexOf(artista)).getAlbumesPublicados().add(new Album(0, tfNombreAlbum.getText(), dateChooserAlbum.getDate(), 0));
            updateClients();
            cbAlbumes.setModel(actualizarComboBoxAlbumes());
            comboBoxAlbumes.setModel(actualizarComboBoxAlbumes());
            JOptionPane.showMessageDialog(dialogClientes, "Album creado");
            tfNombreAlbum.setText("");
        }
    }//GEN-LAST:event_btnCrearAlbumMouseClicked

    private void btnCrearSingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearSingleMouseClicked
        if (tfNombreSingle.getText().isEmpty()) {
            JOptionPane.showMessageDialog(dialogClientes, "Debe llenar todos los campos");
        } else {
            artistas.get(artistas.indexOf(artista)).getCancionesSubidas().add(new Single(tfNombreSingle.getText(), dateChooserSingle.getDate(), 0));
            updateClients();
            cbSingles.setModel(actualizarComboBoxSingles());
            comboBoxSingles.setModel(actualizarComboBoxSingles());
            JOptionPane.showMessageDialog(dialogClientes, "Single creado");
            tfNombreSingle.setText("");
        }
    }//GEN-LAST:event_btnCrearSingleMouseClicked

    private void btnCrearCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCancionMouseClicked
        if (tfNombreCancion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(dialogClientes, "Debe llenar todos los campos");
        } else {
            String nombreCancion = tfNombreCancion.getText();
            int tiempoDuracion = (int) spinnerTiempoDuracion.getValue();
            if (rbAlbum.isSelected()) {
                canciones.add(new Cancion(nombreCancion, tiempoDuracion, (Album) cbAlbumes.getSelectedItem()));
                cbCanciones.setModel(actualizarComboBoxCanciones());
                
            } else if (rbSingle.isSelected()){
                canciones.add(new Cancion(nombreCancion, tiempoDuracion, (Single) cbSingles.getSelectedItem()));
                cbCanciones.setModel(actualizarComboBoxCanciones());
            }
            JOptionPane.showMessageDialog(dialogClientes, "Cancion creada correctamente");
        }
    }//GEN-LAST:event_btnCrearCancionMouseClicked

    private void btnReproducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReproducirMouseClicked

        ab = new adminBarra(pbReproduccion, 0, jPanel1);
        pbReproduccion.setMaximum(7);
        UIManager.put("nimbusOrange", Color.YELLOW);
        ab.setVive(true);
        ab.setTiempo(6);
        ab.start();
            
    }//GEN-LAST:event_btnReproducirMouseClicked

    public DefaultComboBoxModel actualizarComboBoxLanzamientos() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Lanzamiento lanzamiento : lanzamientos) {
            modelo.addElement(lanzamiento);
        }
        return modelo;
    }

    public DefaultComboBoxModel actualizarComboBoxListasRP() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (ListasDeReproduccion listasRP : listasDeReproduccion) {
            modelo.addElement(listasRP);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel actualizarComboBoxAlbumes() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Album album : artistas.get(artistas.indexOf(artista)).getAlbumesPublicados()) {
            modelo.addElement(album);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel actualizarComboBoxSingles() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Single single : artistas.get(artistas.indexOf(artista)).getCancionesSubidas()) {
            modelo.addElement(single);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel actualizarComboBoxCanciones() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Cancion cancion : canciones) {
            modelo.addElement(cancion);
        }
        return modelo;
    }
    
    public DefaultListModel actualizarList(){
        DefaultListModel modelo = new DefaultListModel();
        for (ListasDeReproduccion listasDeReproduccion1 : listasDeReproduccion) {
            modelo.addAll(listasDeReproduccion);
        }
        return modelo;
    }

    private void updateArtists() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            File fichero = new File("./artistas.coc");
            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);
            bw.writeObject(artistas);
            bw.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }

    private void readArtists() {
        File fichero = new File("./artistas.coc");
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        if (fichero.exists()) {
            try {
                entrada = new FileInputStream(fichero);
                objeto = new ObjectInputStream(entrada);
                artistas = (ArrayList<Artista>) objeto.readObject();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                objeto.close();
                entrada.close();
            } catch (IOException ex) {
            }
        }
    }

    private void updateClients() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            File fichero = new File("./clientes.coc");
            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);
            bw.writeObject(clientes);
            bw.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }

    private void readClients() {
        File fichero = new File("./clientes.coc");
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        if (fichero.exists()) {
            try {
                entrada = new FileInputStream(fichero);
                objeto = new ObjectInputStream(entrada);
                clientes = (ArrayList<Cliente>) objeto.readObject();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                objeto.close();
                entrada.close();
            } catch (IOException ex) {
            }
        }
    }

    private void bitacora(String usuario, String tipo) {
        File fichero = new File("./bitacora.txt");
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(fichero, true);
            bw = new BufferedWriter(fw);
            bw.write("Se creo el usuario: " + usuario + " con el tipo : " + tipo + " y con fecha de creacion: " + new Date().toString());
            bw.flush();
        } catch (Exception e) {
        }
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAlbum;
    private javax.swing.JButton btnCrearCancion;
    private javax.swing.JButton btnCrearLanzamiento;
    private javax.swing.JButton btnCrearListaRP;
    private javax.swing.JButton btnCrearSingle;
    private javax.swing.JButton btnEliminarLanzamiento;
    private javax.swing.JButton btnEliminarListaRP;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnModificarLanzamiento;
    private javax.swing.JButton btnModificarListaRP;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterArtist;
    private javax.swing.JButton btnRegisterClient;
    private javax.swing.JButton btnReproducir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAlbumes;
    private javax.swing.JComboBox<String> cbCanciones;
    private javax.swing.JComboBox<String> cbLanzamientos;
    private javax.swing.JComboBox<String> cbListasRP;
    private javax.swing.JComboBox<String> cbSingles;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> comboBoxAlbumes;
    private javax.swing.JComboBox<String> comboBoxSingles;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateChooserAlbum;
    private com.toedter.calendar.JDateChooser dateChooserModify;
    private com.toedter.calendar.JDateChooser dateChooserSingle;
    private javax.swing.JDialog dialogArtistas;
    private javax.swing.JDialog dialogClientes;
    private javax.swing.JDialog dialogRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListCanciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JProgressBar pbReproduccion;
    private javax.swing.JPasswordField pwfContraseñaArtista;
    private javax.swing.JPasswordField pwfContraseñaCliente;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JRadioButton rbAlbum;
    private javax.swing.JRadioButton rbSingle;
    private javax.swing.JSpinner spinnerTiempoDuracion;
    private javax.swing.JTextField tfEdadArtista;
    private javax.swing.JTextField tfEdadCliente;
    private javax.swing.JTextField tfNombreAlbum;
    private javax.swing.JTextField tfNombreArtistico;
    private javax.swing.JTextField tfNombreCancion;
    private javax.swing.JTextField tfNombreDeLista;
    private javax.swing.JTextField tfNombreSingle;
    private javax.swing.JTextField tfNuevoNombreListaRP;
    private javax.swing.JTextField tfNuevoTituloLanzamiento;
    private javax.swing.JTextField tfTituloLanzamiento;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfUsuarioArtista;
    private javax.swing.JTextField tfUsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
